export const dummyPantryItems = [
  {
    id: "1",
    name: "Brown Rice",
    category: "Grains",
    quantity: 2,
    unit: "kg",
    expiresAt: "2025-11-01",
  },
  {
    id: "2",
    name: "Canned Tomatoes",
    category: "Canned Goods",
    quantity: 4,
    unit: "cans",
    expiresAt: "2026-02-15",
  },
  {
    id: "3",
    name: "Peanut Butter",
    category: "Spreads",
    quantity: 1,
    unit: "jar",
    expiresAt: "2025-07-20",
  },
  {
    id: "4",
    name: "Black Beans",
    category: "Canned Goods",
    quantity: 3,
    unit: "cans",
    expiresAt: "2026-01-10",
  },
  {
    id: "5",
    name: "Olive Oil",
    category: "Oils",
    quantity: 1,
    unit: "liter",
    expiresAt: "2026-08-30",
  },
  {
    id: "6",
    name: "Salt",
    category: "Spices",
    quantity: 1,
    unit: "kg",
    expiresAt: null,
  },
  {
    id: "7",
    name: "All-Purpose Flour",
    category: "Baking",
    quantity: 2,
    unit: "kg",
    expiresAt: "2025-09-18",
  },
  {
    id: "8",
    name: "Baking Powder",
    category: "Baking",
    quantity: 1,
    unit: "pack",
    expiresAt: "2025-12-05",
  },
  {
    id: "9",
    name: "Honey",
    category: "Sweeteners",
    quantity: 1,
    unit: "jar",
    expiresAt: null,
  },
  {
    id: "10",
    name: "Soy Sauce",
    category: "Condiments",
    quantity: 1,
    unit: "bottle",
    expiresAt: "2026-05-14",
  },
  {
    id: "11",
    name: "Pasta",
    category: "Grains",
    quantity: 3,
    unit: "packs",
    expiresAt: "2025-10-12",
  },
  {
    id: "12",
    name: "Chickpeas",
    category: "Canned Goods",
    quantity: 2,
    unit: "cans",
    expiresAt: "2026-03-09",
  },
  {
    id: "13",
    name: "Oats",
    category: "Grains",
    quantity: 1,
    unit: "kg",
    expiresAt: "2025-06-01",
  },
  {
    id: "14",
    name: "Vanilla Extract",
    category: "Baking",
    quantity: 1,
    unit: "bottle",
    expiresAt: "2027-01-01",
  },
  {
    id: "15",
    name: "Coconut Milk",
    category: "Canned Goods",
    quantity: 2,
    unit: "cans",
    expiresAt: "2026-04-20",
  },
];
