name: CI

on: [push]

jobs:
  run tests:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

      - name: Install Node Modules
        run: npm ci

      - name: Run Tests
        run: npm test
