name: CI

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Node Modules
        run: npm ci  # Faster and recommended for CI/CD

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
